---
- name: Retrieving status of Confluence directory to see if it exists
  stat:
    path: "{{ home_dir }}"
  register: p

# Backup is created in install-confluence.yml
- name: Delete Confluence directory if it exists
  file:
    path: "{{ home_dir }}"
    state: absent
  when: p.stat.isdir is defined and p.stat.isdir

- name: Transfer backup file to application-data directory
  copy:
    src: "{{ file_path }}/{{ file_name }}"
    dest: "{{ data_dir }}/application-data/{{ file_name }}"

- name: Unarchive install file
  unarchive:
    src: "{{ data_dir }}/application-data/{{ file_name }}"
    dest: "{{ data_dir }}/application-data/"
    remote_src: true
    owner: "{{ os_confluence_user }}"
    group: "{{ os_confluence_group }}"

- name: Cleanup
  file:
    path: "{{ data_dir }}/application-data/{{ file_name }}"
    state: absent
